version: '3.8'

services:
  web:
    build: .
    container_name: elon_berish_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app    # Mount code for live edits (optional)
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs appear immediately
    restart: unless-stopped
